version: '3.8'

services:
  # Redis for queue management
  redis:
    image: redis:7-alpine
    container_name: crewai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChromaDB for vector storage
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: crewai-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Llama.cpp server for LLM services
  llama-server:
    build:
      context: .
      dockerfile: Dockerfile.llama-cpp
    container_name: crewai-llama-server
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./models:/app/models:ro
      - llama-logs:/app/logs
    environment:
      - LLAMA_PROFILE=${LLAMA_PROFILE:-balanced}
      - LLAMA_MODEL=${LLAMA_MODEL:-llama-3.2-3b-instruct.Q4_K_M.gguf}
      - LLAMA_PORT=8081
      - LLAMA_HOST=0.0.0.0
    networks:
      - crewai-network
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '12'
        reservations:
          memory: 8G
          cpus: '8'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV:-development}
    container_name: crewai-app
    restart: unless-stopped
    ports:
      - "3000:3000"     # Frontend
      - "3001:3001"     # API
      - "8080:8080"     # WebSocket
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_PATH=/app/data/crewai_enhanced.db
      - WALMART_DB_PATH=/app/data/walmart_grocery.db
      - REDIS_URL=redis://redis:6379
      - CHROMA_URL=http://chromadb:8000
      - LLAMA_SERVER_URL=http://llama-server:8081
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
      - ./src:/app/src:ro  # Mount source for development
      - ./public:/app/public:ro
    depends_on:
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      llama-server:
        condition: service_healthy
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx reverse proxy (production)
  nginx:
    image: nginx:alpine
    container_name: crewai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - crewai-network
    profiles:
      - production

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: crewai-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - crewai-network
    profiles:
      - monitoring

  # Grafana for visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: crewai-grafana
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - crewai-network
    profiles:
      - monitoring

volumes:
  app-data:
    driver: local
  app-logs:
    driver: local
  redis-data:
    driver: local
  chromadb-data:
    driver: local
  llama-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  nginx-cache:
    driver: local

networks:
  crewai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16