version: '3.8'

services:
  # Redis Service - Session management and caching
  redis:
    image: redis:7.2-alpine
    container_name: crewai-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - crewai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ChromaDB Service - Vector store for RAG
  chromadb:
    image: chromadb/chroma:0.4.24
    container_name: crewai-chromadb
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token.TokenAuthServerProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS=test-token
      - CHROMA_SERVER_AUTH_TOKEN_HEADER_NAME=X-Chroma-Token
    networks:
      - crewai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/heartbeat || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Ollama Service - Local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: crewai-ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
    networks:
      - crewai-network
    restart: unless-stopped
    # Uncomment below if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # SearXNG Service - Private search engine
  searxng:
    image: searxng/searxng:latest
    container_name: crewai-searxng
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      - ./data/searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8888/
      - INSTANCE_NAME=CrewAI Search
    networks:
      - crewai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
    driver: local
  ollama_data:
    driver: local

networks:
  crewai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16