version: '3.8'

services:
  # Ollama service for integration tests
  ollama-test:
    image: ollama/ollama:latest
    container_name: crewai-ollama-test
    ports:
      - "11434:11434"
    volumes:
      - ollama-test-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_NUM_PARALLEL=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ChromaDB for vector storage tests
  chromadb-test:
    image: chromadb/chroma:latest
    container_name: crewai-chromadb-test
    ports:
      - "8000:8000"
    environment:
      - ANONYMIZED_TELEMETRY=false
      - ALLOW_RESET=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Redis for caching tests
  redis-test:
    image: redis:7-alpine
    container_name: crewai-redis-test
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  ollama-test-data:
    driver: local