# Prometheus configuration for Walmart Grocery Agent monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'walmart-grocery-monitor'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 15s

  # Walmart Grocery Services
  - job_name: 'walmart-services'
    static_configs:
      - targets:
        - 'localhost:3000'  # API Server
        - 'localhost:3006'  # Cache Warmer
        - 'localhost:3007'  # Pricing Service
        - 'localhost:3008'  # NLP Queue
        - 'localhost:3009'  # Memory Monitor
        - 'localhost:8080'  # WebSocket
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is installed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    scrape_interval: 30s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s