# 2025 Best Practice: AlertManager configuration for production alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: '${SLACK_WEBHOOK_URL}'
      
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default-receiver'
      routes:
      - match:
          severity: critical
        receiver: critical-receiver
        continue: true
      - match:
          severity: warning
        receiver: warning-receiver
        continue: true
      - match:
          team: email-team
        receiver: email-team-receiver
        
    receivers:
    - name: 'default-receiver'
      webhook_configs:
      - url: 'http://webhook-receiver.monitoring.svc.cluster.local/webhook'
        
    - name: 'critical-receiver'
      slack_configs:
      - channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
        color: 'danger'
      pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
          
    - name: 'warning-receiver'
      slack_configs:
      - channel: '#alerts-warning'
        title: 'Warning Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
        color: 'warning'
        
    - name: 'email-team-receiver'
      slack_configs:
      - channel: '#email-dashboard-alerts'
        title: 'Email Dashboard Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Instance:* {{ .CommonLabels.instance }}
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
        send_resolved: true
      webhook_configs:
      - url: '${TEAMS_WEBHOOK_URL}'
        
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
      
    templates:
    - '/etc/alertmanager/templates/*.tmpl'

---
# Alert Templates
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{ define "email.default.subject" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }} for {{ .GroupLabels.job }}
    {{ end }}

    {{ define "email.default.html" }}
    <h2>{{ .GroupLabels.alertname }}</h2>
    <table border="1">
    <tr><th>Alert</th><th>Instance</th><th>Severity</th><th>Description</th><th>Status</th></tr>
    {{ range .Alerts }}
    <tr>
      <td>{{ .Labels.alertname }}</td>
      <td>{{ .Labels.instance }}</td>
      <td>{{ .Labels.severity }}</td>
      <td>{{ .Annotations.description }}</td>
      <td>{{ .Status }}</td>
    </tr>
    {{ end }}
    </table>
    {{ end }}

    {{ define "slack.default.title" }}
    {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
    {{ end }}

    {{ define "slack.default.text" }}
    {{ range .Alerts }}
    *Alert:* {{ .Labels.alertname }}
    *Instance:* {{ .Labels.instance }}
    *Description:* {{ .Annotations.description }}
    *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
    {{ end }}
    {{ end }}