# Prometheus Alerting Rules for Walmart Grocery Agent

groups:
  - name: walmart_grocery_agent_alerts
    rules:
      # High-level service health alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.job }} service on {{ $labels.instance }} has been down for more than 1 minute."

      # Application-specific alerts
      - alert: HighResponseTime
        expr: walmart_app_response_time_ms > 5000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "Walmart app response time is {{ $value }}ms, which exceeds 5000ms threshold."

      - alert: HighErrorRate
        expr: rate(walmart_app_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes."

      # Memory and CPU alerts
      - alert: HighMemoryUsage
        expr: (walmart_app_memory_usage_bytes / walmart_app_memory_limit_bytes) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} of available memory."

      - alert: HighCPUUsage
        expr: walmart_app_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% over the last 5 minutes."

      # Database-specific alerts
      - alert: DatabaseConnectionFailure
        expr: walmart_app_database_connections_failed_total > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failures"
          description: "{{ $value }} database connection failures in the last minute."

      - alert: SlowDatabaseQueries
        expr: walmart_app_database_query_duration_ms > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Database queries are taking {{ $value }}ms on average."

      # WebSocket connection alerts
      - alert: WebSocketConnectionDrop
        expr: rate(walmart_websocket_disconnections_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High WebSocket disconnection rate"
          description: "WebSocket disconnection rate is {{ $value }} per second."

      # NLP Service alerts
      - alert: NLPServiceHighLatency
        expr: nlp_service_request_duration_ms > 3000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "NLP service high latency"
          description: "NLP service latency is {{ $value }}ms, exceeding 3000ms threshold."

      - alert: NLPAccuracyDrop
        expr: nlp_service_accuracy_percent < 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "NLP accuracy below threshold"
          description: "NLP accuracy has dropped to {{ $value }}%, below 80% threshold."

      # Pricing Service alerts
      - alert: PricingServiceUnavailable
        expr: pricing_service_api_calls_failed_total > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pricing service failures"
          description: "{{ $value }} pricing service failures in the last minute."

      # Cache performance alerts
      - alert: CacheHitRateLow
        expr: cache_hit_rate_percent < 70
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Cache hit rate below threshold"
          description: "Cache hit rate is {{ $value }}%, below 70% threshold."

      # Redis alerts
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection failure"
          description: "No Redis clients connected for more than 1 minute."

      # Storage alerts
      - alert: DiskSpaceLow
        expr: walmart_app_disk_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space running low"
          description: "Disk usage is {{ $value }}%, approaching capacity."

  - name: walmart_business_metrics
    rules:
      # Business-specific alerts
      - alert: LowOrderProcessingRate
        expr: rate(walmart_orders_processed_total[10m]) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low order processing rate"
          description: "Order processing rate has dropped to {{ $value }} orders per second."

      - alert: HighPriceUpdateFailures
        expr: rate(walmart_price_updates_failed_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High price update failure rate"
          description: "Price update failure rate is {{ $value }} per second."

      - alert: SearchResultsQualityDrop
        expr: walmart_search_results_quality_score < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Search results quality degraded"
          description: "Search results quality score is {{ $value }}, below 0.8 threshold."