#define REDIS_GIT_SHA1 "5d547a44"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "NPAMD-1753291175"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
