#!/bin/bash
# Migrate Knowledge Base to Ubuntu_EXT
# This script consolidates all knowledge bases to Ubuntu_EXT

set -e

echo "🚀 Knowledge Base Migration to Ubuntu_EXT"
echo "========================================"
echo ""

# Configuration
LOCAL_KB="/home/pricepro2006/master_knowledge_base"
CREWAI_LOCAL_KB="/home/pricepro2006/CrewAI_Team/master_knowledge_base"
MOUNT_POINT="/mnt/ubuntu_ext"
REMOTE_KB="${MOUNT_POINT}/home/pricepro2006/master_knowledge_base"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Check if mount exists
if [ ! -d "$MOUNT_POINT" ]; then
    echo "❌ Ubuntu_EXT not mounted. Please run setup-cross-distro-knowledge-base.sh first"
    exit 1
fi

echo "📊 Current Storage Status:"
echo "-------------------------"
df -h / /mnt/c "$MOUNT_POINT" 2>/dev/null | grep -E "Filesystem|%" || true
echo ""

# Function to safely migrate data
migrate_data() {
    local source="$1"
    local dest="$2"
    local name="$3"
    
    if [ ! -d "$source" ]; then
        echo "⏭️  Skipping $name (not found)"
        return
    fi
    
    echo "📁 Migrating $name..."
    echo "   Source: $source"
    echo "   Destination: $dest"
    
    # Create destination directory
    mkdir -p "$dest"
    
    # Count files
    local file_count=$(find "$source" -type f | wc -l)
    echo "   Files to migrate: $file_count"
    
    # Perform migration with progress
    if [ $file_count -gt 0 ]; then
        rsync -av --progress "$source/" "$dest/"
        echo "   ✅ Migrated $file_count files"
    else
        echo "   ⏭️  No files to migrate"
    fi
    echo ""
}

# Main migration process
echo "🔄 Starting Migration Process..."
echo ""

# 1. Check if Ubuntu_EXT is accessible
echo "1️⃣ Checking Ubuntu_EXT accessibility..."
if [ -d "$REMOTE_KB" ]; then
    echo "   ✅ Ubuntu_EXT master_knowledge_base exists"
else
    echo "   📁 Creating master_knowledge_base on Ubuntu_EXT..."
    mkdir -p "$REMOTE_KB"
fi

# 2. Migrate local Ubuntu knowledge base
echo ""
echo "2️⃣ Migrating local Ubuntu knowledge base..."
if [ -d "$LOCAL_KB" ]; then
    migrate_data "$LOCAL_KB" "$REMOTE_KB" "Ubuntu local KB"
else
    echo "   ⏭️  No local Ubuntu KB found"
fi

# 3. Migrate CrewAI local knowledge base
echo "3️⃣ Migrating CrewAI Team local knowledge base..."
if [ -d "$CREWAI_LOCAL_KB" ]; then
    # This appears to be January 2025 specific knowledge
    migrate_data "$CREWAI_LOCAL_KB" "$REMOTE_KB/CrewAI_Team/january_2025_knowledge" "CrewAI local KB"
else
    echo "   ⏭️  No CrewAI local KB found"
fi

# 4. Create migration summary
echo "4️⃣ Creating migration summary..."
cat > "$REMOTE_KB/MIGRATION_LOG_${TIMESTAMP}.md" << EOF
# Knowledge Base Migration Log
Date: $(date)

## Migration Summary
- Migrated from Ubuntu (local) to Ubuntu_EXT
- Reason: Storage constraints on Windows drive (100% full)

## Sources Migrated
1. **Ubuntu Local KB**: $LOCAL_KB
   - Status: $([ -d "$LOCAL_KB" ] && echo "Migrated" || echo "Not found")
   
2. **CrewAI Local KB**: $CREWAI_LOCAL_KB  
   - Status: $([ -d "$CREWAI_LOCAL_KB" ] && echo "Migrated to january_2025_knowledge" || echo "Not found")

## Storage Status Post-Migration
$(df -h "$MOUNT_POINT" | tail -1)

## Next Steps
1. Remove local copies after verifying migration
2. Update all scripts to use unified KB
3. Setup regular backups on Ubuntu_EXT

---
Generated by migrate-to-ubuntu-ext-kb.sh
EOF

# 5. Verify migration
echo ""
echo "5️⃣ Verifying migration..."
echo "   Master KB structure on Ubuntu_EXT:"
tree -L 3 "$REMOTE_KB" 2>/dev/null | head -20 || ls -la "$REMOTE_KB"

# 6. Create cleanup script
echo ""
echo "6️⃣ Creating cleanup script..."
cat > "$HOME/cleanup-local-kb.sh" << 'EOF'
#!/bin/bash
# Cleanup local knowledge bases after successful migration

echo "⚠️  WARNING: This will remove local knowledge base copies"
echo "   Please ensure migration to Ubuntu_EXT was successful!"
echo ""
read -p "Are you sure you want to proceed? (yes/no) " -r
echo ""

if [[ $REPLY == "yes" ]]; then
    echo "🗑️  Removing local copies..."
    
    # Remove Ubuntu local KB
    if [ -d "/home/pricepro2006/master_knowledge_base" ]; then
        rm -rf "/home/pricepro2006/master_knowledge_base"
        echo "   ✅ Removed Ubuntu local KB"
    fi
    
    # Remove CrewAI local KB
    if [ -d "/home/pricepro2006/CrewAI_Team/master_knowledge_base" ]; then
        rm -rf "/home/pricepro2006/CrewAI_Team/master_knowledge_base"
        echo "   ✅ Removed CrewAI local KB"
    fi
    
    echo ""
    echo "✅ Cleanup complete!"
    echo "   All knowledge now centralized on Ubuntu_EXT"
else
    echo "❌ Cleanup cancelled"
fi
EOF
chmod +x "$HOME/cleanup-local-kb.sh"

# Summary
echo ""
echo "✅ Migration Complete!"
echo "===================="
echo ""
echo "📊 Summary:"
echo "   - All knowledge bases migrated to Ubuntu_EXT"
echo "   - Migration log saved to: $REMOTE_KB/MIGRATION_LOG_${TIMESTAMP}.md"
echo "   - Cleanup script created at: ~/cleanup-local-kb.sh"
echo ""
echo "🎯 Next Steps:"
echo "   1. Verify the migration was successful"
echo "   2. Run ~/cleanup-local-kb.sh to remove local copies"
echo "   3. All future knowledge should be saved to: ~/master_knowledge_base"
echo "      (This will be a symlink to Ubuntu_EXT after setup)"
echo ""
echo "💡 Remember: The master_knowledge_base is now on Ubuntu_EXT with plenty of storage!"

# Make this script executable
chmod +x "$0"